### PR TITLE
chore: remove `moment` dependency

### LINKED ISSUE #117: Remove unused dependency moment.js

### PR DESCRIPTION
**Pull request by joaonmatos**
Closes #117

### CODE REVIEW

**Comment by TiagooGomess** [comment]
I'm using this package in my PR

**Comment by imnotteixeira** [comment]
> I'm using this package in #105

You should use date-fns (already installed, check ApplicationsReviewWidget, for example). Moment.js is deprecated.

**Comment by TiagooGomess** [comment]
> > I'm using this package in #105
> 
> You should use date-fns (already installed, check ApplicationsReviewWidget, for example). Moment.js is deprecated.

I'm not sure if I can use this format with that package:
Screenshot from 2021-08-04 18-56-05
Screenshot from 2021-08-04 18-56-17

**Comment by joaonmatos** [comment]
You might still consider a different option. Consider this docs page:

https://momentjs.com/docs/#/-project-status/

The project is currently on maintenance mode. If you look in the date fn documentation, particularly on the format function, you might find something to answer your question.

**Comment by imnotteixeira** [comment]
> > > I'm using this package in #105
> > 
> > 
> > You should use date-fns (already installed, check ApplicationsReviewWidget, for example). Moment.js is deprecated.
> 
> I'm not sure if I can use this format with that package:
> Screenshot from 2021-08-04 18-56-05
> Screenshot from 2021-08-04 18-56-17

From the front page of date-fns https://date-fns.org/
```js
formatDistance(subDays(new Date(), 3), new Date(), { addSuffix: true })
//=> "3 days ago"
```

Isn't this your use case?

**Comment by imnotteixeira** [comment]
https://date-fns.org/v2.23.0/docs/formatDistanceToNow actually this might be better

**Review by imnotteixeira — APPROVED** [review]

**Pull request merged**
