### PR TITLE
Changed scroll behavior to include SearchURLWidget

### PR DESCRIPTION
**Pull request by Naapperas**
Fixes the weird scrolling behavior currently merged to the `develop` branch.

### CODE REVIEW

**Comment by Naapperas** [comment]
Gonna change the UrlSearchWidget to use a modal.

**Comment by BrunoRosendo** [comment]
@Naapperas I'm pretty sure these buttons should wrap in mobile view. Can you take a look at it

image

**Comment by Naapperas** [comment]
@BrunoRosendo I think I managed to fix most of the styles, please take a look. This needs to be merged ASAP so we do not delay this release any further.

**Review by BrunoRosendo — APPROVED** [review]
Great job!

**Pull request merged**
