### PR TITLE
Fix no Margin in the Offer Page, in Production

### LINKED ISSUE #170: No Margin in the Offer Page, in Production
image

Try one of the following
- Update MUI
- Increase specificity

### PR DESCRIPTION
**Pull request by TiagooGomess**
Closes #170

### CODE REVIEW

**Comment by TiagooGomess** [comment]
Did not work

**Comment by TiagooGomess** [comment]
I think there are more CSS problems:

**Comment by TiagooGomess** [comment]
This fixed the problem:

image

**Comment by TiagooGomess** [comment]
> I think there are more CSS problems:
> 
> 

Fixed using the same method

**Review by DoStini — APPROVED** [review]

**Pull request merged**
