### PR TITLE
Changed skeleton package

### LINKED ISSUE #52: Change skeleton package, to use MUI skeleton functionality
Currently, OfferItem uses `react-loading-skeleton` package to render the loading skeleton. We should use the MUI version, since we already use the rest of the package.

### PR DESCRIPTION
**Pull request by CarlosMealha**
closes #52

### CODE REVIEW

**Comment by CarlosMealha** [comment]
I've just changed the react skeleton package to the `{Skeleton} from @material-ui/lab`, but I'm not 100% sure if this is the correct one.

**Review by TiagooGomess — APPROVED** [review]
Yes, that's the correct one.

**Review by TiagooGomess — CHANGES_REQUESTED** [review]
You should rebase to remove the 26a2b1b245e92575569098486c03e3a3826adddd commit.

**Comment by CarlosMealha** [comment]
Okay thank for the correction, I think it's working now!

**Comment by imnotteixeira** [comment]
Need to `git fetch` and `git rebase origin/develop` as well to sync the latest changes

**Comment by CarlosMealha** [comment]
I don't know why, but it keeps saying that everything is up to date, even with the commands that you have said.

**Comment by CarlosMealha** [comment]
I even tried to `git pull origin master` and `git push origin <BRANCH>`. And nothing has changed

**Comment by TiagooGomess** [comment]
Try these commands:
- git checkout develop
- git pull origin develop
- git checkout <YOUR-BRANCH>
- git rebase develop
- git push origin <YOUR-BRANCH> --force-with-lease

**Comment by CarlosMealha** [comment]
Yeah it worked, thank you!

**Review by TiagooGomess — APPROVED** [review]

**Review by TiagooGomess — CHANGES_REQUESTED** [review]
You should also remove the `react-loading-skeleton` package from the `package.json` file. For that, you can use the command `npm uninstall react-loading-skeleton`. Make sure you have node version `14.18.3` to execute the command.

**Review by TiagooGomess — APPROVED** [review]
I promise it's my final review :sweat_smile:

**Comment by CarlosMealha** [comment]
😂

**Comment by imnotteixeira** [comment]
Be more careful with commit messages... Seems like we removed react itself

**Pull request merged**
