### PR TITLE
Feature/boilerplate 1

### LINKED ISSUE #1: Boilerplate code
Create a React App with the following features:

- [x] Prod Environment, which builds the app to static files

- [x] Dev Environment with hot reloading

- [x] Redux 

- [x] React Router

- [x] Material UI (@material-ui/core)

### PR DESCRIPTION
**Pull request by miguelpduarte**
Closes #1 

Adds React, Redux, React Router, and MaterialUI to the project (used `create-react-app` and then added other dependencies "by hand").

Covers most use cases with example code:
* Redux actions and reducers (async and non async actions with and without payloads, different reducers, usage in components for showing data using state, calling actions in components)
* React components that use MaterialUI components
* Routing with React Router (the `pages` directory holds the pages and the `components` directory holds the components displayed in the pages) to pages with and without URL params, showing off the "no-reload page changing" of SPAs
* Added examples of CSS Modules usage (currently only for components, but can also be used for the whole app, for example for different sizings or colors)

`README.md` might need updating in order to clarify the project structure.

### CODE REVIEW

**Comment by imnotteixeira** [comment]
Added messages/notifications functionality to show messages to the user. See:
- https://material.io/design/components/snackbars.html
- https://github.com/iamhosseindhv/notistack

Also fixed unintended horizontal scrolling when using grids (for example in home page)

**Comment by miguelpduarte** [comment]
This looks good, I believe it can be merged now, what do you think? @imnotteixeira

**Comment by imnotteixeira** [comment]
@miguelpduarte I think an explanation of the boilerplate components and "How to use" details should be added. I will work on that, then it'll be ready for merge

**Comment by miguelpduarte** [comment]
(Finally) added the section explaining CSS Modules. I have reviewed the remainder of BOILERPLATE.md and the rest of the project and it looks good to go. @imnotteixeira opinions?

**Pull request merged**
