### PR TITLE
fixed divider bug

### LINKED ISSUE #277: Divider between list of offers and offer details disappears when scrolling
The divider between the list of search results and its details is too small and disappears when scrolling.

The offending element is [this divider](https://github.com/NIAEFEUP/nijobs-fe/blob/f022998f43346e75405afe6aae7d0ca6c42a21ba/src/components/HomePage/SearchResultsArea/SearchResultsWidget/SearchResultsDesktop.js#L39).

image image

### PR DESCRIPTION
**Pull request by diogofonte**
Closes #277 

[Video:](https://user-images.githubusercontent.com/93329645/215620751-9936c6bf-c9ef-4615-93c6-94ac96034e81.mp4)

### CODE REVIEW

**Comment by BrunoRosendo** [comment]
Please fix the linting errors preventing the build to succeed.

Additionally, can you record a video with more offers? What I want is to check if the scrollbar still works when we load more offers (after the defined offer limit defined somewhere)

**Comment by diogofonte** [comment]
The lint error is fixed.

Here is a new demo video:

[new demo video:](https://user-images.githubusercontent.com/93329645/215817085-80af0bb5-b08f-4aa7-8d63-3e2349f9a951.mp4)

**Review by Naapperas — APPROVED** [review]
LGTM

**Comment by Naapperas** [comment]
Rebase and then this is ready to be merged @diogofonte

**Comment by diogofonte** [comment]
Rebase done

**Pull request merged**
